name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#      - name: Install tox
#        run: |
#          python -m pip install --upgrade pip
#          python -m pip install --upgrade tox
#      - name: Run pre-commit linting
#        run: tox -e pre-commit

#  test_python_36:
#    runs-on: ubuntu-20.04
#    name: Python 3.6
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.6
#          architecture: x64
#      - name: Install tox
#        run: |
#          python -m pip install --upgrade pip
#          python -m pip install --upgrade tox tox-py
#      - name: Run tests
#        run: tox --py 36

  test_python_39:
    runs-on: ubuntu-22.04
    name: PyPy 3.9
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
          architecture: x64
      - name: Set C headers path
        run: |
          PYPY_VERSION=$(pypy3.9 -c 'import sys; print(*sys.version_info[:3], sep=".")')
          echo "C_HEADERS_PATH=$RUNNER_TOOL_CACHE/PyPy/$PYPY_VERSION/x64/include:$C_HEADERS_PATH" >> $GITHUB_ENV
          ls $RUNNER_TOOL_CACHE/PyPy/
          ls $RUNNER_TOOL_CACHE/PyPy/$PYPY_VERSION/x64/
          ls $RUNNER_TOOL_CACHE/PyPy/$PYPY_VERSION/x64/include
          ls $C_HEADERS_PATH
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade 'tox>=4.0'
          python -m pip install --upgrade --no-binary :all: coverage
      - name: Run tests
        run: tox run -f pypy39

#  test:
#    runs-on: ubuntu-22.04
#    strategy:
#      matrix:
#        python-version:
#          - 3.7
#          - 3.8
#          - 3.9
#          - '3.10'
#          - '3.11'
#    name: Python ${{ matrix.python-version }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ matrix.python-version }}
#          architecture: x64
#      - name: Install tox
#        run: |
#          python -m pip install --upgrade pip
#          python -m pip install --upgrade 'tox>=4.0'
#      - name: Run tests
#        run: tox run -f py$(echo ${{ matrix.python-version }} | tr -d .)
