name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox
      - name: Run pre-commit linting
        run: tox -e pre-commit

  test_python_36:
    runs-on: ubuntu-20.04
    name: Python 3.6
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox tox-py
      - name: Run tests
        run: tox --py 36

  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
          - '3.11'
          - 'pypy3.9'
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade 'tox>=4.0'
      - name: Run tests
        run: tox run -f py$(echo ${{ matrix.python-version }} | tr -d .)
